name: Generate Release Package

on:
  push:
    tags:
    - '*'

jobs:
  release-gen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install deps
        run: |
          yarn
      - name: Build and generate artifact
        run: |
          yarn vscode:publish
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "vscode-remote-resolver*.vsix"
